[2024-05-31 02:41:02] [DEBUG] UART initialized with port: /dev/ttyS2 and baudrate: 115200
[2024-05-31 02:41:02] [DEBUG] Added command number: 1 with function: test1 and release_port_during_execution: True
[2024-05-31 02:41:02] [DEBUG] Added command number: 2 with function: test2 and release_port_during_execution: False
[2024-05-31 02:41:02] [DEBUG] Added command number: 3 with function: execute_capture_command and release_port_during_execution: False
[2024-05-31 02:41:02] [DEBUG] Added command number: 4 with function: pic2point and release_port_during_execution: False
[2024-05-31 02:41:02] [INFO] Listening for incoming commands
[2024-05-31 02:41:02] [INFO] UART listener started.
[2024-05-31 02:41:47] [WARNING] Command timeout occurred
[2024-05-31 02:41:47] [DEBUG] Executing command: +3+/home/sky/capture:str+640:str+320:str+6:str+black:str+10:str+
[2024-05-31 02:41:47] [DEBUG] Parsing command: +3+/home/sky/capture:str+640:str+320:str+6:str+black:str+10:str+
[2024-05-31 02:41:47] [DEBUG] Received command from UART: +3+/home/sky/capture:str+640:str+320:str+6:str+black:str+10:str+
[2024-05-31 02:41:47] [DEBUG] Parsed command number: 3 with arguments: ['/home/sky/capture', '640', '320', '6', 'black', '10']
[2024-05-31 02:41:47] [INFO] Executing capture command: python3 /home/sky/satcont_main/camera/capture/capture.py /home/sky/capture 640 320 6 black 10
[2024-05-31 02:41:56] [INFO] [EXTERNAL] /home/sky/capture/capture_5.jpg

[2024-05-31 02:41:56] [INFO] Command executed successfully: 3
[2024-05-31 02:47:12] [WARNING] Command timeout occurred
[2024-05-31 02:47:12] [DEBUG] Executing command: +3+/home/sky/capture:str+640:str+320:str+6:str+black:str+10:str+
[2024-05-31 02:47:12] [DEBUG] Parsing command: +3+/home/sky/capture:str+640:str+320:str+6:str+black:str+10:str+
[2024-05-31 02:47:12] [DEBUG] Received command from UART: +3+/home/sky/capture:str+640:str+320:str+6:str+black:str+10:str+
[2024-05-31 02:47:12] [DEBUG] Parsed command number: 3 with arguments: ['/home/sky/capture', '640', '320', '6', 'black', '10']
[2024-05-31 02:47:12] [INFO] Executing capture command: python3 /home/sky/satcont_main/camera/capture/capture.py /home/sky/capture 640 320 6 black 10
[2024-05-31 02:47:19] [INFO] [EXTERNAL] /home/sky/capture/capture_6.jpg

[2024-05-31 02:47:19] [INFO] Command executed successfully: 3
[2024-05-31 02:47:47] [WARNING] Command timeout occurred
[2024-05-31 02:47:47] [DEBUG] Executing command: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:47:47] [DEBUG] Parsing command: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:47:47] [DEBUG] Received command from UART: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:47:47] [DEBUG] Parsed command number: 3 with arguments: ['/home/sky/capture', '640', '320', '4', 'black', '10']
[2024-05-31 02:47:47] [INFO] Executing capture command: python3 /home/sky/satcont_main/camera/capture/capture.py /home/sky/capture 640 320 4 black 10
[2024-05-31 02:47:55] [INFO] [EXTERNAL] /home/sky/capture/capture_7.jpg

[2024-05-31 02:47:55] [INFO] Command executed successfully: 3
[2024-05-31 02:48:08] [WARNING] Command timeout occurred
[2024-05-31 02:48:08] [DEBUG] Executing command: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:48:08] [DEBUG] Parsing command: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:48:08] [DEBUG] Received command from UART: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:48:08] [DEBUG] Parsed command number: 3 with arguments: ['/home/sky/capture', '640', '320', '4', 'black', '10']
[2024-05-31 02:48:08] [INFO] Executing capture command: python3 /home/sky/satcont_main/camera/capture/capture.py /home/sky/capture 640 320 4 black 10
[2024-05-31 02:48:15] [INFO] [EXTERNAL] /home/sky/capture/capture_8.jpg

[2024-05-31 02:48:15] [INFO] Command executed successfully: 3
[2024-05-31 02:48:26] [WARNING] Command timeout occurred
[2024-05-31 02:48:37] [WARNING] Command timeout occurred
[2024-05-31 02:48:51] [WARNING] Command timeout occurred
[2024-05-31 02:49:00] [DEBUG] Executing command: +
[2024-05-31 02:49:00] [DEBUG] Parsing command: +
[2024-05-31 02:49:00] [DEBUG] Received command from UART: +
[2024-05-31 02:49:00] [ERROR] Error during command execution: invalid literal for int() with base 10: ''
[2024-05-31 02:49:00] [ERROR] Sending error message: invalid literal for int() with base 10: ''
[2024-05-31 02:49:15] [WARNING] Command timeout occurred
[2024-05-31 02:49:16] [DEBUG] Executing command: +
[2024-05-31 02:49:16] [DEBUG] Parsing command: +
[2024-05-31 02:49:16] [DEBUG] Received command from UART: +
[2024-05-31 02:49:16] [ERROR] Error during command execution: invalid literal for int() with base 10: ''
[2024-05-31 02:49:16] [ERROR] Sending error message: invalid literal for int() with base 10: ''
[2024-05-31 02:49:18] [DEBUG] Executing command: +
[2024-05-31 02:49:18] [DEBUG] Parsing command: +
[2024-05-31 02:49:18] [DEBUG] Received command from UART: +
[2024-05-31 02:49:18] [ERROR] Error during command execution: invalid literal for int() with base 10: ''
[2024-05-31 02:49:18] [ERROR] Sending error message: invalid literal for int() with base 10: ''
[2024-05-31 02:49:18] [DEBUG] Executing command: 3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:49:18] [DEBUG] Parsing command: 3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:49:18] [DEBUG] Received command from UART: 3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:49:18] [DEBUG] Parsed command number: 3 with arguments: ['/home/sky/capture', '640', '320', '4', 'black', '10']
[2024-05-31 02:49:18] [INFO] Executing capture command: python3 /home/sky/satcont_main/camera/capture/capture.py /home/sky/capture 640 320 4 black 10
[2024-05-31 02:49:26] [INFO] [EXTERNAL] /home/sky/capture/capture_9.jpg

[2024-05-31 02:49:26] [INFO] Command executed successfully: 3
[2024-05-31 02:49:50] [WARNING] Command timeout occurred
[2024-05-31 02:49:50] [DEBUG] Executing command: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:49:50] [DEBUG] Parsing command: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:49:50] [DEBUG] Received command from UART: +3+/home/sky/capture:str+640:str+320:str+4:str+black:str+10:str+
[2024-05-31 02:49:50] [DEBUG] Parsed command number: 3 with arguments: ['/home/sky/capture', '640', '320', '4', 'black', '10']
[2024-05-31 02:49:50] [INFO] Executing capture command: python3 /home/sky/satcont_main/camera/capture/capture.py /home/sky/capture 640 320 4 black 10
[2024-05-31 02:49:57] [INFO] [EXTERNAL] /home/sky/capture/capture_10.jpg

[2024-05-31 02:49:57] [INFO] Command executed successfully: 3
